<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.vgrytsenko2022</groupId>
        <artifactId>netbeans-flutter-plugin</artifactId>
        <version>0.1.3</version>
    </parent>
    <artifactId>flutter-designer</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>io.github.vgrytsenko2022</groupId>
            <artifactId>flutter-core-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>${project.basedir}/../docs/flutter-designer</directory>
                <includes>
                    <include>fd-v2.schema.json</include>
                    <include>fd-v3.schema.json</include>
                    <include>fd-v4.schema.json</include>
                    <include>fd-v5.schema.json</include>
                    <include>fd-v6.schema.json</include>
                    <include>fd-v7.schema.json</include>
                    <include>fd-v8.schema.json</include>
                    <include>fd-v9.schema.json</include>
                    <include>fd-v10.schema.json</include>
                    <include>fd-v11.schema.json</include>
                    <include>fd-v12.schema.json</include>
                    <include>fd-v13.schema.json</include>
                    <include>fd-v14.schema.json</include>
                    <include>fd-v15.schema.json</include>
                    <include>fd-v16.schema.json</include>
                    <include>fd-v17.schema.json</include>
                </includes>
                <targetPath>META-INF/netbeans-flutter-designer/schema</targetPath>
                <filtering>false</filtering>
            </resource>
        </resources>
    </build>
    <version>0.1.3</version>
    <groupId>io.github.vgrytsenko2022</groupId>
</project>
