package dev.flutter.netbeans.plugin.designer.icons;

import dev.flutter.netbeans.designer.catalog.GridViewCountWidgetPropertySchema;
import dev.flutter.netbeans.designer.catalog.GridViewExtentWidgetPropertySchema;
import dev.flutter.netbeans.designer.catalog.SingleChildScrollViewWidgetPropertySchema;
import dev.flutter.netbeans.designer.catalog.PageViewWidgetPropertySchema;
import dev.flutter.netbeans.designer.catalog.CustomScrollViewWidgetPropertySchema;
import dev.flutter.netbeans.designer.model.WidgetTypeId;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Central mapping between reviewed built-in widget identities and their
 * NetBeans icon bases.
 *
 * <p>Each base has a 16 px SVG, a {@code 32} SVG used for larger palette
 * presentations, and matching {@code _dark} variants. Extension widgets are
 * deliberately left unmapped rather than being mistaken for one of the
 * reviewed core widgets; a validated contributor-icon SPI is a later slice.</p>
 */
public final class FlutterWidgetIconRegistry {
    private static final String ICON_ROOT =
            "dev/flutter/netbeans/plugin/designer/icons/widgets/";

    private static final Map<String, String> REVIEWED_ICON_PATHS = Map.ofEntries(
            Map.entry("flutter.material.Scaffold", ICON_ROOT + "scaffold.svg"),
            Map.entry("flutter.material.AppBar", ICON_ROOT + "appbar.svg"),
            Map.entry("flutter.material.FlexibleSpaceBar", ICON_ROOT + "flexiblespacebar.svg"),
            Map.entry("flutter.material.FlexibleSpaceBarSettings", ICON_ROOT + "flexiblespacebarsettings.svg"),
            Map.entry("flutter.material.SliverAppBar", ICON_ROOT + "sliverappbar.svg"),
            Map.entry("flutter.material.SliverAppBar.medium", ICON_ROOT + "sliverappbarmedium.svg"),
            Map.entry("flutter.material.SliverAppBar.large", ICON_ROOT + "sliverappbarlarge.svg"),
            Map.entry("flutter.material.ElevatedButton",
                    ICON_ROOT + "elevatedbutton.svg"),
            Map.entry("flutter.material.TextField", ICON_ROOT + "textfield.svg"),
            Map.entry("flutter.widgets.Column", ICON_ROOT + "column.svg"),
            Map.entry("flutter.widgets.Row", ICON_ROOT + "row.svg"),
            Map.entry("flutter.widgets.Wrap", ICON_ROOT + "wrap.svg"),
            Map.entry("flutter.widgets.Padding", ICON_ROOT + "padding.svg"),
            Map.entry("flutter.widgets.Center", ICON_ROOT + "center.svg"),
            Map.entry("flutter.widgets.Align", ICON_ROOT + "align.svg"),
            Map.entry("flutter.widgets.FractionallySizedBox",
                    ICON_ROOT + "fractionallysizedbox.svg"),
            Map.entry("flutter.widgets.FittedBox", ICON_ROOT + "fittedbox.svg"),
            Map.entry("flutter.widgets.ConstrainedBox",
                    ICON_ROOT + "constrainedbox.svg"),
            Map.entry("flutter.widgets.UnconstrainedBox",
                    ICON_ROOT + "unconstrainedbox.svg"),
            Map.entry("flutter.widgets.LimitedBox", ICON_ROOT + "limitedbox.svg"),
            Map.entry("flutter.widgets.OverflowBox", ICON_ROOT + "overflowbox.svg"),
            Map.entry("flutter.widgets.Stack", ICON_ROOT + "stack.svg"),
            Map.entry("flutter.widgets.IndexedStack",
                    ICON_ROOT + "indexedstack.svg"),
            Map.entry("flutter.widgets.Expanded", ICON_ROOT + "expanded.svg"),
            Map.entry("flutter.widgets.Flexible", ICON_ROOT + "flexible.svg"),
            Map.entry("flutter.widgets.Spacer", ICON_ROOT + "spacer.svg"),
            Map.entry("flutter.widgets.Baseline", ICON_ROOT + "baseline.svg"),
            Map.entry("flutter.widgets.IntrinsicHeight",
                    ICON_ROOT + "intrinsicheight.svg"),
            Map.entry("flutter.widgets.IntrinsicWidth",
                    ICON_ROOT + "intrinsicwidth.svg"),
            Map.entry("flutter.widgets.Offstage", ICON_ROOT + "offstage.svg"),
            Map.entry("flutter.widgets.SizedOverflowBox",
                    ICON_ROOT + "sizedoverflowbox.svg"),
            Map.entry("flutter.widgets.Transform", ICON_ROOT + "transform.svg"),
            Map.entry("flutter.widgets.RotatedBox", ICON_ROOT + "rotatedbox.svg"),
            Map.entry("flutter.widgets.PreferredSize", ICON_ROOT + "preferredsize.svg"),
            Map.entry("flutter.widgets.Builder", ICON_ROOT + "builder.svg"),
            Map.entry("flutter.widgets.ListBody", ICON_ROOT + "listbody.svg"),
            Map.entry("flutter.widgets.OverflowBar", ICON_ROOT + "overflowbar.svg"),
            Map.entry("flutter.widgets.SafeArea", ICON_ROOT + "safearea.svg"),
            Map.entry("flutter.widgets.ListView", ICON_ROOT + "listview.svg"),
            Map.entry(GridViewCountWidgetPropertySchema.GRID_VIEW_COUNT_TYPE.value(),
                    ICON_ROOT + "gridviewcount.svg"),
            Map.entry(GridViewExtentWidgetPropertySchema.GRID_VIEW_EXTENT_TYPE.value(),
                    ICON_ROOT + "gridviewextent.svg"),
            Map.entry(
                    SingleChildScrollViewWidgetPropertySchema
                            .SINGLE_CHILD_SCROLL_VIEW_TYPE.value(),
                    ICON_ROOT + "singlechildscrollview.svg"),
            Map.entry(PageViewWidgetPropertySchema.PAGE_VIEW_TYPE.value(),
                    ICON_ROOT + "pageview.svg"),
            Map.entry("flutter.widgets.ListWheelScrollView", ICON_ROOT + "listwheelscrollview.svg"),
            Map.entry(CustomScrollViewWidgetPropertySchema.CUSTOM_SCROLL_VIEW_TYPE.value(), ICON_ROOT + "customscrollview.svg"),
            Map.entry("flutter.widgets.SliverToBoxAdapter", ICON_ROOT + "slivertoboxadapter.svg"),
            Map.entry("flutter.widgets.SliverIgnorePointer", ICON_ROOT + "sliverignorepointer.svg"),
            Map.entry("flutter.widgets.SliverOffstage", ICON_ROOT + "sliveroffstage.svg"),
            Map.entry("flutter.widgets.SliverSafeArea", ICON_ROOT + "sliversafearea.svg"),
            Map.entry("flutter.widgets.AnimatedAlign", ICON_ROOT + "animatedalign.svg"),
            Map.entry("flutter.widgets.AnimatedFractionallySizedBox", ICON_ROOT + "animatedfractionallysizedbox.svg"),
            Map.entry("flutter.widgets.AnimatedPadding", ICON_ROOT + "animatedpadding.svg"),
            Map.entry("flutter.widgets.AnimatedSlide", ICON_ROOT + "animatedslide.svg"),
            Map.entry("flutter.widgets.AnimatedScale", ICON_ROOT + "animatedscale.svg"),
            Map.entry("flutter.widgets.AnimatedRotation", ICON_ROOT + "animatedrotation.svg"),
            Map.entry("flutter.widgets.AnimatedPositioned", ICON_ROOT + "animatedpositioned.svg"),
            Map.entry("flutter.widgets.AnimatedPositioned.fromRect", ICON_ROOT + "animatedpositionedrect.svg"),
            Map.entry("flutter.widgets.AnimatedPositionedDirectional", ICON_ROOT + "animatedpositioneddirectional.svg"),
            Map.entry("flutter.widgets.AnimatedDefaultTextStyle", ICON_ROOT + "animateddefaulttextstyle.svg"),
            Map.entry("flutter.widgets.DefaultTextStyle", ICON_ROOT + "defaulttextstyle.svg"),
            Map.entry("flutter.widgets.RotationTransition", ICON_ROOT + "rotationtransition.svg"),
            Map.entry("flutter.widgets.SizeTransition", ICON_ROOT + "sizetransition.svg"),
            Map.entry("flutter.widgets.PositionedTransition", ICON_ROOT + "positionedtransition.svg"),
            Map.entry("flutter.widgets.DecoratedBoxTransition", ICON_ROOT + "decoratedboxtransition.svg"),
            Map.entry("flutter.widgets.AlignTransition", ICON_ROOT + "aligntransition.svg"),
            Map.entry("flutter.widgets.MatrixTransition", ICON_ROOT + "matrixtransition.svg"),
            Map.entry("flutter.widgets.ModalBarrier", ICON_ROOT + "modalbarrier.svg"),
            Map.entry("flutter.widgets.AnimatedModalBarrier", ICON_ROOT + "animatedmodalbarrier.svg"),
            Map.entry("flutter.widgets.FadeInImage", ICON_ROOT + "fadeinimage.svg"),
            Map.entry("flutter.widgets.RawImage", ICON_ROOT + "rawimage.svg"),
            Map.entry("flutter.widgets.ColorFiltered", ICON_ROOT + "colorfiltered.svg"),
            Map.entry("flutter.widgets.ImageFiltered", ICON_ROOT + "imagefiltered.svg"),
            Map.entry("flutter.widgets.BackdropFilter", ICON_ROOT + "backdropfilter.svg"),
            Map.entry("flutter.widgets.BackdropFilter.grouped", ICON_ROOT + "backdropfiltergrouped.svg"),
            Map.entry("flutter.widgets.BackdropGroup", ICON_ROOT + "backdropgroup.svg"),
            Map.entry("flutter.widgets.ShaderMask", ICON_ROOT + "shadermask.svg"),
            Map.entry("flutter.widgets.CustomPaint", ICON_ROOT + "custompaint.svg"),
            Map.entry("flutter.widgets.LayoutId", ICON_ROOT + "layoutid.svg"),
            Map.entry("flutter.widgets.CustomMultiChildLayout", ICON_ROOT + "custommultichildlayout.svg"),
            Map.entry("flutter.material.PaginatedDataTable", ICON_ROOT + "paginateddatatable.svg"),
            Map.entry("flutter.material.DataTable", ICON_ROOT + "datatable.svg"),
            Map.entry("flutter.material.DataColumn", ICON_ROOT + "datacolumn.svg"),
            Map.entry("flutter.material.DataRow", ICON_ROOT + "datarow.svg"),
            Map.entry("flutter.material.DataRow.byIndex", ICON_ROOT + "datarowbyindex.svg"),
            Map.entry("flutter.material.DataCell", ICON_ROOT + "datacell.svg"),
            Map.entry("flutter.material.DataCell.empty", ICON_ROOT + "datacellempty.svg"),
            Map.entry("flutter.widgets.Table", ICON_ROOT + "table.svg"),
            Map.entry("flutter.widgets.TableRow", ICON_ROOT + "tablerow.svg"),
            Map.entry("flutter.widgets.TableCell", ICON_ROOT + "tablecell.svg"),
            Map.entry("flutter.widgets.Flow", ICON_ROOT + "flow.svg"),
            Map.entry("flutter.widgets.Flow.unwrapped", ICON_ROOT + "flowunwrapped.svg"),
            Map.entry("flutter.widgets.CustomSingleChildLayout", ICON_ROOT + "customsinglechildlayout.svg"),
            Map.entry("flutter.material.AnimatedIcon", ICON_ROOT + "animatedicon.svg"),
            Map.entry("flutter.widgets.RelativePositionedTransition", ICON_ROOT + "relativepositionedtransition.svg"),
            Map.entry("flutter.widgets.ScaleTransition", ICON_ROOT + "scaletransition.svg"),
            Map.entry("flutter.widgets.SlideTransition", ICON_ROOT + "slidetransition.svg"),
            Map.entry("flutter.widgets.FadeTransition", ICON_ROOT + "fadetransition.svg"),
            Map.entry("flutter.widgets.SliverFadeTransition", ICON_ROOT + "sliverfadetransition.svg"),
            Map.entry("flutter.widgets.DefaultTextStyleTransition", ICON_ROOT + "defaulttextstyletransition.svg"),
            Map.entry("flutter.widgets.DefaultTextStyle.merge", ICON_ROOT + "defaulttextstylemerge.svg"),
            Map.entry("flutter.widgets.AnimatedPhysicalModel", ICON_ROOT + "animatedphysicalmodel.svg"),
            Map.entry("flutter.widgets.AnimatedSize", ICON_ROOT + "animatedsize.svg"),
            Map.entry("flutter.widgets.AnimatedCrossFade", ICON_ROOT + "animatedcrossfade.svg"),
            Map.entry("flutter.widgets.AnimatedSwitcher", ICON_ROOT + "animatedswitcher.svg"),
            Map.entry("flutter.material.AnimatedTheme", ICON_ROOT + "animatedtheme.svg"),
            Map.entry("flutter.material.Theme", ICON_ROOT + "theme.svg"),
            Map.entry("flutter.widgets.AnimatedContainer", ICON_ROOT + "animatedcontainer.svg"),
            Map.entry("flutter.widgets.AnimatedOpacity", ICON_ROOT + "animatedopacity.svg"),
            Map.entry("flutter.widgets.SliverAnimatedOpacity", ICON_ROOT + "sliveranimatedopacity.svg"),
            Map.entry("flutter.widgets.LayoutBuilder", ICON_ROOT + "layoutbuilder.svg"),
            Map.entry("flutter.widgets.OrientationBuilder", ICON_ROOT + "orientationbuilder.svg"),
            Map.entry("flutter.widgets.ValueListenableBuilder", ICON_ROOT + "valuelistenablebuilder.svg"),
            Map.entry("flutter.widgets.ValueListenableBuilder.sliver", ICON_ROOT + "slivervaluelistenablebuilder.svg"),
            Map.entry("flutter.widgets.TweenAnimationBuilder", ICON_ROOT + "tweenanimationbuilder.svg"),
            Map.entry("flutter.widgets.TweenAnimationBuilder.sliver", ICON_ROOT + "slivertweenanimationbuilder.svg"),
            Map.entry("flutter.widgets.AnimatedBuilder", ICON_ROOT + "animatedbuilder.svg"),
            Map.entry("flutter.widgets.AnimatedBuilder.sliver", ICON_ROOT + "sliveranimatedbuilder.svg"),
            Map.entry("flutter.widgets.ListenableBuilder", ICON_ROOT + "listenablebuilder.svg"),
            Map.entry("flutter.widgets.ListenableBuilder.sliver", ICON_ROOT + "sliverlistenablebuilder.svg"),
            Map.entry("flutter.widgets.DeviceOrientationBuilder", ICON_ROOT + "deviceorientationbuilder.svg"),
            Map.entry("flutter.widgets.DeviceOrientationBuilder.sliver", ICON_ROOT + "sliverdeviceorientationbuilder.svg"),
            Map.entry("flutter.widgets.SliverLayoutBuilder", ICON_ROOT + "sliverlayoutbuilder.svg"),
            Map.entry("flutter.widgets.SliverPersistentHeader", ICON_ROOT + "sliverpersistentheader.svg"),
            Map.entry("flutter.widgets.SliverFloatingHeader", ICON_ROOT + "sliverfloatingheader.svg"),
            Map.entry("flutter.widgets.PinnedHeaderSliver", ICON_ROOT + "pinnedheadersliver.svg"),
            Map.entry("flutter.widgets.SliverResizingHeader", ICON_ROOT + "sliverresizingheader.svg"),
            Map.entry("flutter.widgets.SliverVisibility", ICON_ROOT + "slivervisibility.svg"),
            Map.entry("flutter.widgets.SliverVisibility.maintain", ICON_ROOT + "slivervisibilitymaintain.svg"),
            Map.entry("flutter.widgets.SliverOpacity", ICON_ROOT + "sliveropacity.svg"),
            Map.entry("flutter.widgets.SliverPadding", ICON_ROOT + "sliverpadding.svg"),
            Map.entry("flutter.widgets.SliverFillRemaining", ICON_ROOT + "sliverfillremaining.svg"),
            Map.entry("flutter.widgets.SliverFillViewport", ICON_ROOT + "sliverfillviewport.svg"),
            Map.entry("flutter.widgets.SliverFillViewport.delegate", ICON_ROOT + "sliverfillviewportdelegate.svg"),
            Map.entry("flutter.widgets.SliverMainAxisGroup", ICON_ROOT + "slivermainaxisgroup.svg"),
            Map.entry("flutter.widgets.SliverCrossAxisGroup", ICON_ROOT + "slivercrossaxisgroup.svg"),
            Map.entry("flutter.widgets.SliverConstrainedCrossAxis", ICON_ROOT + "sliverconstrainedcrossaxis.svg"),
            Map.entry("flutter.widgets.SliverCrossAxisExpanded", ICON_ROOT + "slivercrossaxisexpanded.svg"),
            Map.entry("flutter.widgets.SliverFixedExtentList", ICON_ROOT + "sliverfixedextentlist.svg"),
            Map.entry("flutter.widgets.SliverVariedExtentList", ICON_ROOT + "slivervariedextentlist.svg"),
            Map.entry("flutter.widgets.SliverPrototypeExtentList", ICON_ROOT + "sliverprototypeextentlist.svg"),
            Map.entry("flutter.widgets.SliverFixedExtentList.builder", ICON_ROOT + "sliverfixedextentbuilder.svg"),
            Map.entry("flutter.widgets.SliverVariedExtentList.builder", ICON_ROOT + "slivervariedextentbuilder.svg"),
            Map.entry("flutter.widgets.SliverPrototypeExtentList.builder", ICON_ROOT + "sliverprototypeextentbuilder.svg"),
            Map.entry("flutter.widgets.SliverFixedExtentList.delegate", ICON_ROOT + "sliverfixedextentdelegate.svg"),
            Map.entry("flutter.widgets.SliverVariedExtentList.delegate", ICON_ROOT + "slivervariedextentdelegate.svg"),
            Map.entry("flutter.widgets.SliverPrototypeExtentList.delegate", ICON_ROOT + "sliverprototypeextentdelegate.svg"),
            Map.entry("flutter.widgets.SliverList", ICON_ROOT + "sliverlist.svg"),
            Map.entry("flutter.widgets.SliverGrid", ICON_ROOT + "slivergrid.svg"),
            Map.entry("flutter.widgets.SliverGrid.extent", ICON_ROOT + "slivergridextent.svg"),
            Map.entry("flutter.widgets.SliverList.builder", ICON_ROOT + "list_builder.svg"),
            Map.entry("flutter.widgets.SliverList.separated", ICON_ROOT + "list_separated.svg"),
            Map.entry("flutter.widgets.SliverList.delegate", ICON_ROOT + "list_delegate.svg"),
            Map.entry("flutter.widgets.SliverGrid.builder", ICON_ROOT + "grid_builder.svg"),
            Map.entry("flutter.widgets.SliverGrid.list", ICON_ROOT + "grid_list.svg"),
            Map.entry("flutter.widgets.SliverGrid.delegate", ICON_ROOT + "grid_delegate.svg"),
            Map.entry("flutter.widgets.Text", ICON_ROOT + "text.svg"),
            Map.entry("flutter.widgets.Icon", ICON_ROOT + "icon.svg"),
            Map.entry("flutter.widgets.Image", ICON_ROOT + "image.svg"),
            Map.entry("flutter.widgets.ImageIcon", ICON_ROOT + "imageicon.svg"),
            Map.entry("flutter.material.Divider", ICON_ROOT + "divider.svg"),
            Map.entry("flutter.material.VerticalDivider", ICON_ROOT + "verticaldivider.svg"),
            Map.entry("flutter.material.Card", ICON_ROOT + "card.svg"),
            Map.entry("flutter.material.Badge", ICON_ROOT + "badge.svg"),
            Map.entry("flutter.material.CircleAvatar", ICON_ROOT + "circleavatar.svg"),
            Map.entry("flutter.material.LinearProgressIndicator", ICON_ROOT + "linearprogressindicator.svg"),
            Map.entry("flutter.material.CircularProgressIndicator", ICON_ROOT + "circularprogressindicator.svg"),
            Map.entry("flutter.material.RefreshProgressIndicator", ICON_ROOT + "refreshprogressindicator.svg"),
            Map.entry("flutter.material.RefreshIndicator", ICON_ROOT + "refreshindicator.svg"),
            Map.entry("flutter.material.TextButton", ICON_ROOT + "textbutton.svg"),
            Map.entry("flutter.material.OutlinedButton", ICON_ROOT + "outlinedbutton.svg"),
            Map.entry("flutter.material.FilledButton", ICON_ROOT + "filledbutton.svg"),
            Map.entry("flutter.material.FloatingActionButton", ICON_ROOT + "floatingactionbutton.svg"),
            Map.entry("flutter.material.IconButton", ICON_ROOT + "iconbutton.svg"),
            Map.entry("flutter.material.Checkbox", ICON_ROOT + "checkbox.svg"),
            Map.entry("flutter.material.Switch", ICON_ROOT + "switch.svg"),
            Map.entry("flutter.material.Slider", ICON_ROOT + "slider.svg"),
            Map.entry("flutter.material.RangeSlider", ICON_ROOT + "rangeslider.svg"),
            Map.entry("flutter.material.Radio", ICON_ROOT + "radio.svg"),
            Map.entry("flutter.widgets.RadioGroup", ICON_ROOT + "radio_group.svg"),
            Map.entry("flutter.material.ListTile", ICON_ROOT + "list_tile.svg"),
            Map.entry("flutter.material.CheckboxListTile", ICON_ROOT + "checkbox_list_tile.svg"),
            Map.entry("flutter.material.SwitchListTile", ICON_ROOT + "switch_list_tile.svg"),
            Map.entry("flutter.material.RadioListTile", ICON_ROOT + "radio_list_tile.svg"),
            Map.entry("flutter.material.ExpansionTile", ICON_ROOT + "expansion_tile.svg"),
            Map.entry("flutter.material.Tooltip", ICON_ROOT + "tooltip.svg"),
            Map.entry("flutter.material.TooltipVisibility", ICON_ROOT + "tooltipvisibility.svg"),
            Map.entry("flutter.material.TooltipTheme", ICON_ROOT + "tooltiptheme.svg"),
            Map.entry("flutter.material.MenuItemButton", ICON_ROOT + "menuitembutton.svg"),
            Map.entry("flutter.material.MenuAnchor", ICON_ROOT + "menuanchor.svg"),
            Map.entry("flutter.material.SubmenuButton", ICON_ROOT + "submenubutton.svg"),
            Map.entry("flutter.material.MenuBar", ICON_ROOT + "menubar.svg"),
            Map.entry("flutter.material.NavigationBar", ICON_ROOT + "navigationbar.svg"),
            Map.entry("flutter.material.NavigationRail", ICON_ROOT + "navigationrail.svg"),
            Map.entry("flutter.material.NavigationDrawer", ICON_ROOT + "navigationdrawer.svg"),
            Map.entry("flutter.material.Drawer", ICON_ROOT + "drawer.svg"),
            Map.entry("flutter.material.BottomAppBar", ICON_ROOT + "bottomappbar.svg"),
            Map.entry("flutter.material.BottomNavigationBar", ICON_ROOT + "bottomnavigationbar.svg"),
            Map.entry("flutter.material.Material", ICON_ROOT + "material.svg"),
            Map.entry("flutter.material.Scrollbar", ICON_ROOT + "scrollbar.svg"),
            Map.entry("flutter.widgets.ColoredBox", ICON_ROOT + "coloredbox.svg"),
            Map.entry("flutter.widgets.Placeholder", ICON_ROOT + "placeholder.svg"),
            Map.entry("flutter.widgets.Directionality", ICON_ROOT + "directionality.svg"),
            Map.entry("flutter.widgets.DecoratedBox", ICON_ROOT + "decoratedbox.svg"),
            Map.entry("flutter.widgets.ClipRect", ICON_ROOT + "cliprect.svg"),
            Map.entry("flutter.widgets.ClipOval", ICON_ROOT + "clipoval.svg"),
            Map.entry("flutter.widgets.ClipRRect", ICON_ROOT + "cliprrect.svg"),
            Map.entry("flutter.widgets.ClipPath", ICON_ROOT + "clippath.svg"),
            Map.entry("flutter.widgets.ClipRSuperellipse", ICON_ROOT + "cliprsuperellipse.svg"),
            Map.entry("flutter.widgets.PhysicalModel", ICON_ROOT + "physicalmodel.svg"),
            Map.entry("flutter.widgets.PhysicalShape", ICON_ROOT + "physicalshape.svg"),
            Map.entry("flutter.widgets.RepaintBoundary", ICON_ROOT + "repaintboundary.svg"),
            Map.entry("flutter.widgets.MergeSemantics", ICON_ROOT + "mergesemantics.svg"),
            Map.entry("flutter.widgets.IndexedSemantics", ICON_ROOT + "indexedsemantics.svg"),
            Map.entry("flutter.widgets.ExcludeFocus", ICON_ROOT + "excludefocus.svg"),
            Map.entry("flutter.widgets.ExcludeFocusTraversal", ICON_ROOT + "excludefocustraversal.svg"),
            Map.entry("flutter.widgets.Visibility", ICON_ROOT + "visibility.svg"),
            Map.entry("flutter.widgets.TickerMode", ICON_ROOT + "tickermode.svg"),
            Map.entry("flutter.widgets.DefaultTextHeightBehavior", ICON_ROOT + "defaulttextheightbehavior.svg"),
            Map.entry("flutter.widgets.DefaultSelectionStyle", ICON_ROOT + "defaultselectionstyle.svg"),
            Map.entry("flutter.widgets.IconTheme", ICON_ROOT + "icontheme.svg"),
            Map.entry("flutter.widgets.IgnorePointer", ICON_ROOT + "ignorepointer.svg"),
            Map.entry("flutter.widgets.AbsorbPointer", ICON_ROOT + "absorbpointer.svg"),
            Map.entry("flutter.widgets.GestureDetector", ICON_ROOT + "gesturedetector.svg"),
            Map.entry("flutter.widgets.Listener", ICON_ROOT + "listener.svg"),
            Map.entry("flutter.widgets.MouseRegion", ICON_ROOT + "mouseregion.svg"),
            Map.entry("flutter.widgets.Focus", ICON_ROOT + "focus.svg"),
            Map.entry("flutter.widgets.NotificationListener", ICON_ROOT + "notificationlistener.svg"),
            Map.entry("flutter.widgets.BlockSemantics", ICON_ROOT + "blocksemantics.svg"),
            Map.entry("flutter.widgets.ExcludeSemantics",
                    ICON_ROOT + "excludesemantics.svg"),
            Map.entry("flutter.widgets.SizedBox", ICON_ROOT + "sizedbox.svg"),
            Map.entry("flutter.widgets.AspectRatio", ICON_ROOT + "aspectratio.svg"),
            Map.entry("flutter.widgets.Container", ICON_ROOT + "container.svg"),
            Map.entry("flutter.widgets.Opacity", ICON_ROOT + "opacity.svg"));

    private FlutterWidgetIconRegistry() {
    }

    /**
     * Finds the dedicated icon base for a reviewed built-in widget type.
     * Unknown and extension types safely return an empty result.
     */
    public static Optional<String> findIconPath(WidgetTypeId typeId) {
        Objects.requireNonNull(typeId, "typeId");
        return Optional.ofNullable(REVIEWED_ICON_PATHS.get(typeId.value()));
    }
}
