package dev.flutter.netbeans.designer.command;

/** Stable command identities for diagnostics, telemetry and adapters. */
public enum DesignerCommandKind {
    ADD_WIDGET,
    EDIT_TABLE_GRID,
    EDIT_DATA_TABLE_GRID,
    REMOVE_WIDGET,
    MOVE_WIDGET,
    REPLACE_SLOT_CHILD,
    CLEAR_SLOT_CHILDREN,
    WRAP_WIDGET,
    SET_PROPERTY,
    RESET_PROPERTY,
    PATCH_PROPERTIES,
    CREATE_EVENT_HANDLER,
    CREATE_MENU_ANCHOR_BUILDER,
    RENAME_EVENT_HANDLER,
    CREATE_STATE_BINDING,
    RENAME_STATE_FIELD,
    REMOVE_STATE_BINDING,
    BIND_PROPERTY_TO_STATE,
    REMOVE_PROPERTY_STATE_BINDING
}
