package dev.flutter.netbeans.designer.catalog;

public enum CatalogDiagnosticCode {
    DUPLICATE_CONTRIBUTOR_ID,
    INVALID_CONTRIBUTOR,
    UNSUPPORTED_API_VERSION,
    INVALID_DEFINITION,
    RESERVED_WIDGET_TYPE,
    FOREIGN_WIDGET_NAMESPACE,
    DUPLICATE_WIDGET_TYPE,
    INCONSISTENT_PALETTE_CATEGORY
}
